### PR TITLE
Add a yes/no dialog and use it to prompt for save on exit.

### PR DESCRIPTION
**Pull request by damellis**
@nebgnahz can you try this on Linux? It should be in the cmake files but I'm not sure if the code is correct.

### CODE REVIEW

**Comment by nebgnahz** [comment]
It compiles and runs. But `OF_USING_GTK` flag is not turned on.
Also I am a bit confused in how the `initGTK` and other related functions got resolved here. It makes sense in [ofSystemUtils.cpp](https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworks/utils/ofSystemUtils.cpp#L77) but not if this is a standalone file. I might be missing something here.

**Comment by damellis** [comment]
Hmm, looks like there's some work required. I took a shot at editing the code but we'll still need to set `OF_USING_GTK`. During compilation of openFrameworks, it looks like  `OF_USING_GTK` is set in [config.linux.common.mk](https://github.com/openframeworks/openFrameworks/blob/39edba81295af7c8c37975887d6638458f444e37/libs/openFrameworksCompiled/project/makefileCommon/config.linux.common.mk). Maybe we should just set it manually in our CMake configuration? Or add a similar conditional logic?

@nebgnahz: Can you give it a shot?

**Comment by nebgnahz** [comment]
I got it compiling, but execution failed. I tried to step through:

```
   initGTK();
(gdb) n
(ESP:30924): GLib-GObject-WARNING **: cannot register existing type 'GdkWindow'
(ESP:30924): GLib-GObject-CRITICAL **: g_param_spec_object: assertion 'g_type_is_a (object_type, G_TYPE_OBJECT)' failed                                                                                          
(ESP:30924): GLib-GObject-CRITICAL **: g_object_class_install_property: assertion 'G_IS_PARAM_SPEC (pspec)' failed                                                                                               

    GtkWidget* dialog = gtk_message_dialog_new (NULL, (GtkDialogFlags) 0, GTK_MESSAGE_QUESTION, GTK_BUTTONS_OK_CANCEL, "%s", title.c_str());                                                                     
(gdb) n
(ESP:30924): GLib-GObject-WARNING **: cannot register existing type 'GdkScreen'                                 
(ESP:30924): GLib-CRITICAL **: g_once_init_leave: assertion 'result != 0' failed                                        
(ESP:30924): Gdk-CRITICAL **: IA__gdk_screen_get_default_colormap: assertion 'GDK_IS_SCREEN (screen)' failed                                                                                                     
(ESP:30924): Gdk-CRITICAL **: IA__gdk_colormap_get_visual: assertion 'GDK_IS_COLORMAP (colormap)' failed    
```

Unfortunately I am not familiar with GTK so cannot tell what's going on.

**Comment by damellis** [comment]
Okay, I'm disabling the use of the dialog on Linux and just always prompting for a save file name.

**Pull request merged**
